In [ ]:
#Download basic liberis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
#Create basic Dataset
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=32)

In [ ]:
x

array([[-2.47011067, -0.2523109 ,  1.42928133, ...,  1.04314132,
         1.16645608,  1.37144641],
       [-0.59343231, -0.08509676,  0.75474072, ..., -0.25385575,
         1.33163157, -2.22804908],
       [-0.91853067, -0.43404232,  1.04939371, ...,  0.57501746,
         0.31803006,  0.4142389 ],
       ...,
       [-0.20617212,  0.32275558, -1.66173332, ...,  1.32222361,
        -0.48747351, -1.41247084],
       [ 2.20117969, -0.24747033,  0.07973384, ...,  0.15391402,
         0.16975738,  1.33713518],
       [ 0.81513201, -0.21928333, -1.39426097, ...,  0.14013887,
         0.816497  ,  0.90606812]])

In [ ]:
#Train_split_dateset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=32)

In [ ]:
#Model Traning
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)


LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0])

In [ ]:
#frind the result, accuracy,confusion_matrix ect
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.99
[[ 96   1]
 [  1 102]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99        97
           1       0.99      0.99      0.99       103

    accuracy                           0.99       200
   macro avg       0.99      0.99      0.99       200
weighted avg       0.99      0.99      0.99       200



In [ ]:
mode=LogisticRegression()
penalty=['l1','l2','elasticnet']
solver=['newton-cg','lbfgs','liblinear','sag','saga']
c_values=[100,110,120,130,140]

params=dict(penalty=penalty,solver=solver,C=c_values)

In [ ]:
# Define parameter distributions for RandomizedSearchCV
param_distributions = [
    # Parameters for L1 penalty (liblinear or saga solvers)
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [100, 110, 120, 130, 140]
    },
    # Parameters for L2 penalty (all solvers support L2)
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [100, 110, 120, 130, 140]
    },
    # Parameters for Elastic Net penalty (only saga solver, requires l1_ratio)
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'l1_ratio': [0.1, 0.5, 0.9],
        'C': [100, 110, 120, 130, 140]
    },
    # Parameters for no penalty (newton-cg, lbfgs, sag, saga solvers)
    {
        'penalty': [None],
        'solver': ['newton-cg', 'lbfgs', 'sag', 'saga'],
        'C': [100, 110, 120, 130, 140]
    }
]

# Re-initialize the model to use in RandomizedSearchCV
# It's good practice to pass a base estimator without specific params here,
# as RandomizedSearchCV will handle the parameter combinations.
model_rs = LogisticRegression(max_iter=1000) # Increased max_iter to prevent convergence warnings

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

# Initialize RandomizedSearchCV
# n_iter (number of iterations) controls how many parameter settings are sampled.
# Increase n_iter for a more exhaustive search, but it takes longer.
random_search = RandomizedSearchCV(
    estimator=model_rs,
    param_distributions=param_distributions,
    n_iter=50, # Number of parameter settings that are sampled
    cv=kfold,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1 # Use all available CPU cores
)

# Fit RandomizedSearchCV to the training data
random_search.fit(x_train, y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=LogisticRegression(max_iter=1000), n_iter=50,
                   n_jobs=-1,
                   param_distributions=[{'C': [100, 110, 120, 130, 140],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [100, 110, 120, 130, 140],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'liblinear', 'sag',
                                                    'saga']},
                                        {'C': [100, 110, 120, 130, 140],
                                         'l1_ratio': [0.1, 0.5, 0.9],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']},
                                        {'C': [100, 110, 120, 130, 140],
                                         'penalty': [None],
                                         'solver': ['newton-cg', 'lbfgs', 'sag',
                                                    'saga']}],
                   random_state=42, scoring='accuracy')

In [ ]:
# Display the best parameters and best score found by RandomizedSearchCV
print("Best Parameters: ", random_search.best_params_)
print("Best Score: ", random_search.best_score_)

Best Parameters:  {'solver': 'liblinear', 'penalty': 'l2', 'C': 120}
Best Score:  0.99


In [ ]:
# Evaluate the best model on the test set
best_model = random_search.best_estimator_
y_pred_rs = best_model.predict(x_test)

print("RandomizedSearchCV Test Accuracy:", accuracy_score(y_test, y_pred_rs))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rs))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rs))

RandomizedSearchCV Test Accuracy: 0.99

Confusion Matrix:
 [[ 96   1]
 [  1 102]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        97
           1       0.99      0.99      0.99       103

    accuracy                           0.99       200
   macro avg       0.99      0.99      0.99       200
weighted avg       0.99      0.99      0.99       200



In [ ]:
from sklearn.model_selection import StratifiedKFold
kfold=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)


In [ ]:
##GridSearchCV
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=mode,param_grid=params,cv=kfold,scoring='accuracy')
grid.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 110, 120, 130, 140],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

# **Our Concept: Randomised Search CV**

# Hyperparameter Tuning: Why We Use RandomizedSearchCV

When optimizing a machine learning model, we must find the best configuration parameters (called **hyperparameters**), such as the regularization strength \(C\) or penalty type in Logistic Regression. The two main ways to automate this search are **GridSearchCV** and **RandomizedSearchCV**.


## 1. The Core Problem with GridSearchCV (The Exponential Trap)
GridSearchCV performs an exhaustive search. It acts like a brute-force algorithm that checks every single possible combination you provide in a grid.

###  The Grid Search Calculation
If you have 4 hyperparameters, and you want to test 10 possible values for each using 5-fold cross-validation (\(k=5\)):

\[\text{Total Training Runs} = (10 \times 10 \times 10 \times 10) \times 5 = 50,000 \text{ models}\]

If training a single model takes just 2 seconds, your Colab notebook will freeze or run for **nearly 28 hours** just to finish tuning.

## 2. How RandomizedSearchCV Solves This
Instead of checking every single intersection point on the grid, **RandomizedSearchCV** randomly selects a fixed number of combinations (controlled by the parameter `n_iter`) from a statistical distribution.

### Brute Force Grid vs. Randomized Allocation Diagram

```text
       GRID SEARCH (Exhaustive)              RANDOMIZED SEARCH (Budgeted)
       
       Param 2                               Param 2
          ▲                                     ▲
          │  ●   ●   ●   ●   ●                  │      ●          
          │  ●   ●   ●   ●   ●                  │          ●   ●  
          │  ●   ●   ●   ●   ●                  │  ●              
          │  ●   ●   ●   ●   ●                  │              ●  
          └───────────────────►                 └───────────────────►
                             Param 1                               Param 1
       (Tests all 20 intersections)          (Tests only 5 random points)
```


## 3. Why It Is Mathematically Better
1. **Budget Control:** You explicitly dictate the computing budget via `n_iter`. If you set `n_iter=20`, it will only pick 20 combinations, no matter how massive your parameter pool is.
2. **The "Important vs. Unimportant" Parameter Law:** In most models, only 1 or 2 hyperparameters truly impact performance, while others change very little.
   * **Grid Search** wastes dozens of runs repeating tests on the unimportant parameter.
   * **Randomized Search** explores distinct values across the important parameter space on every single iteration, discovering the optimal setup much faster.


## 4. Scikit-Learn Python Implementation
Copy this code pattern to see how to execute a randomized search for a Logistic Regression classifier:

```python
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

# 1. Define your parameter distribution space
param_distributions = {
    'C': uniform(loc=0.1, scale=10),       # Continuous random distribution between 0.1 and 10.1
    'penalty': ['l1', 'l2'],                # Categorical choices
    'solver': ['liblinear', 'saga']         # Compatible solvers
}

# 2. Initialize the model and randomized search engine
lr = LogisticRegression(max_iter=1000)
random_search = RandomizedSearchCV(
    estimator=lr,
    param_distributions=param_distributions,
    n_iter=15,                             # Explicit budget: test exactly 15 random combinations
    cv=5,                                  # 5-Fold cross-validation
    random_state=42,
    n_jobs=-1                              # Use all available CPU cores to speed it up
)

# 3. Execute the search
# random_search.fit(X_train, y_train)
print("RandomizedSearchCV setup complete.")
```


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
model=LogisticRegression()
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=50,cv=kfold,scoring='accuracy')
randomCV.fit(x_train,y_train)



/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which 

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=LogisticRegression(), n_iter=50,
                   param_distributions={'C': [100, 110, 120, 130, 140],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [ ]:
randomCV.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 100}

In [ ]:
randomCV.best_score_

np.float64(0.99)

In [ ]:
y_pred=randomCV.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.99
[[ 96   1]
 [  1 102]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99        97
           1       0.99      0.99      0.99       103

    accuracy                           0.99       200
   macro avg       0.99      0.99      0.99       200
weighted avg       0.99      0.99      0.99       200

